const initialState = {
    total:0,
    productsCar: [],
    products: [
        {
            "id": 2,
            "name": "In the Dark",
            "price": 2009,
            "cover": "http://dummyimage.com/800x600.png/99118E/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 3,
            "name": "Instinct",
            "price": 2002,
            "cover": "http://dummyimage.com/800x600.png/302140/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 4,
            "name": "Grand Hotel",
            "price": 2014,
            "cover": "http://dummyimage.com/800x600.png/5472FF/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 5,
            "name": "Stargate Atlantis",
            "price": 2014,
            "cover": "http://dummyimage.com/800x600.png/B36F20/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 6,
            "name": "Final Space",
            "price": 2017,
            "cover": "http://dummyimage.com/800x600.png/CCC539/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 7,
            "name": "The InBetween",
            "price": 2011,
            "cover": "http://dummyimage.com/800x600.png/FF7A90/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 8,
            "name": "Stargate Atlantis",
            "price": 2012,
            "cover": "http://dummyimage.com/800x600.png/306880/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 9,
            "name": "Alien Highway",
            "price": 2019,
            "cover": "http://dummyimage.com/800x600.png/604180/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 10,
            "name": "Elementary",
            "price": 2011,
            "cover": "http://dummyimage.com/800x600.png/FF91BA/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 11,
            "name": "Strange Angel",
            "price": 2015,
            "cover": "http://dummyimage.com/800x600.png/45807C/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 12,
            "name": "Private Eyes",
            "price": 2018,
            "cover": "http://dummyimage.com/800x600.png/577380/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
        {
            "id": 13,
            "name": "Tool",
            "price": 20000,
            "cover": "http://dummyimage.com/800x600.png/5472FF/ffffff",
            "shortDescription": "Vestibulum ac est lacinia nisi venenatis tristique",
        },
    ]
}
export default initialState;
